apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: ZGF0YWJhc2UtMS5jcGcyczg2YXU1c3guYXAtc291dGgtMS5yZHMuYW1hem9uYXdzLmNvbQ==
  db_username: YWRtaW4=
  db_password: QWRtaW5wYXNzd29yZDEyMw==
